name = "WaterModelsAnalytics"
uuid = "c8dd6cb9-700f-49b6-9aea-b063ad5cac2e"
authors = ["Jonathan Stickel <jonathan.stickel@nrel.gov>"]
repo = "https://github.com/NREL-SIIP/WaterModelsAnalytics.jl"
version = "0.3.1"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WaterModels = "7c60b362-08f4-5b14-8680-cd67a3e18348"

[compat]
ColorSchemes = "3.10"
ColorTypes = "~0.10, ~0.11"
DataFrames = "1.1"
Interpolations = "0.13"
LaTeXStrings = "1.2"
Memento = "1"
Plots = "1"
PyCall = "1.91"
WaterModels = "~0.6, ~0.7"
julia = "1.6"

[extras]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JSON"]
